openapi: 3.0.3
info:
  version: 1.2.3
  title: EVO Payments

  
servers:
 - 
  description: UAT
  url: https://apiuat.test.boipapaymentgateway.com

paths:
 /payments:
  post:
    tags:
      - payment
    operationId: capturePayment
    description: Process payment
    requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CaptureAction'

    responses:
      '200':
        description: Response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseResponse'

 /token:
  post:
    tags:
      - token
    operationId: getSessionToken
    description: Fetch session token
    requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
             $ref: '#/components/schemas/CaptureSessionToken'

    responses:
      '200':
        description: Response
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseResponse'

components:
  schemas:
    CaptureSessionToken:
      title: CaptureSession Token
      type: object
      required: 
        - merchantId
        - password
        - action
        - timestamp
        - allowOriginUrl
        - amount
      properties:
        merchantId:
          type: integer
          example: 167885
        password:
          type: string
          example: 56789
        action:
          type: string
          example: CAPTURE
        timestamp:
          type: integer
          example: 0
        allowOriginUrl:
          type: string
          example: example.org
        originalTxId:
          type: string
        originalMerchantTxId:
          type: string
        agentId:
          type: string
        amount:
          type: number
          format: double
          example: 10.00

    CaptureAction:
      title: Capture Payment
      type: object
      required: 
        - merchantId
        - password
        - action
        - token
      properties:
        merchantId:
          type: integer
          example: 167885
        token:
          type: string
          example: abcde12345abcde12345
        action:
          type: string
          example: CAPTURE


    TokenResponseProcessed:
      title: Processed
      type: object
      required:
        - result
      properties:
        merchantId:
          type: string
        token:
          type: string
        resultId:
          type: string
        processingTime:
          type: integer
      allOf:
       - $ref: '#/components/schemas/BaseResponse'

    ResponseNotProcessed:
      title: NotProcessed
      type: object
      required:
        - result
      properties:
        merchantId:
          type: string
        processingTime:
          type: integer
      allOf:
       - $ref: '#/components/schemas/BaseResponse'

    BaseResponse:
      type: object
      properties:
        result:
          type: string
      discriminator:
        propertyName: result
        mapping:
          success: '#/components/schemas/TokenResponseProcessed'
          failure: '#/components/schemas/ResponseNotProcessed'


