<?php
/**
 * TokenApi
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVO Payments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * TokenApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TokenApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getSessionToken
     *
     * @param  int $merchant_id merchant_id (required)
     * @param  string $password password (required)
     * @param  string $action action (required)
     * @param  int $timestamp timestamp (required)
     * @param  string $allow_origin_url allow_origin_url (required)
     * @param  double $amount amount (required)
     * @param  string $original_tx_id original_tx_id (optional)
     * @param  string $original_merchant_tx_id original_merchant_tx_id (optional)
     * @param  string $agent_id agent_id (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BaseResponse
     */
    public function getSessionToken($merchant_id, $password, $action, $timestamp, $allow_origin_url, $amount, $original_tx_id = null, $original_merchant_tx_id = null, $agent_id = null)
    {
        list($response) = $this->getSessionTokenWithHttpInfo($merchant_id, $password, $action, $timestamp, $allow_origin_url, $amount, $original_tx_id, $original_merchant_tx_id, $agent_id);
        return $response;
    }

    /**
     * Operation getSessionTokenWithHttpInfo
     *
     * @param  int $merchant_id (required)
     * @param  string $password (required)
     * @param  string $action (required)
     * @param  int $timestamp (required)
     * @param  string $allow_origin_url (required)
     * @param  double $amount (required)
     * @param  string $original_tx_id (optional)
     * @param  string $original_merchant_tx_id (optional)
     * @param  string $agent_id (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BaseResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSessionTokenWithHttpInfo($merchant_id, $password, $action, $timestamp, $allow_origin_url, $amount, $original_tx_id = null, $original_merchant_tx_id = null, $agent_id = null)
    {
        $request = $this->getSessionTokenRequest($merchant_id, $password, $action, $timestamp, $allow_origin_url, $amount, $original_tx_id, $original_merchant_tx_id, $agent_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\BaseResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\BaseResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\BaseResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BaseResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSessionTokenAsync
     *
     * @param  int $merchant_id (required)
     * @param  string $password (required)
     * @param  string $action (required)
     * @param  int $timestamp (required)
     * @param  string $allow_origin_url (required)
     * @param  double $amount (required)
     * @param  string $original_tx_id (optional)
     * @param  string $original_merchant_tx_id (optional)
     * @param  string $agent_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSessionTokenAsync($merchant_id, $password, $action, $timestamp, $allow_origin_url, $amount, $original_tx_id = null, $original_merchant_tx_id = null, $agent_id = null)
    {
        return $this->getSessionTokenAsyncWithHttpInfo($merchant_id, $password, $action, $timestamp, $allow_origin_url, $amount, $original_tx_id, $original_merchant_tx_id, $agent_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSessionTokenAsyncWithHttpInfo
     *
     * @param  int $merchant_id (required)
     * @param  string $password (required)
     * @param  string $action (required)
     * @param  int $timestamp (required)
     * @param  string $allow_origin_url (required)
     * @param  double $amount (required)
     * @param  string $original_tx_id (optional)
     * @param  string $original_merchant_tx_id (optional)
     * @param  string $agent_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSessionTokenAsyncWithHttpInfo($merchant_id, $password, $action, $timestamp, $allow_origin_url, $amount, $original_tx_id = null, $original_merchant_tx_id = null, $agent_id = null)
    {
        $returnType = '\OpenAPI\Client\Model\BaseResponse';
        $request = $this->getSessionTokenRequest($merchant_id, $password, $action, $timestamp, $allow_origin_url, $amount, $original_tx_id, $original_merchant_tx_id, $agent_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSessionToken'
     *
     * @param  int $merchant_id (required)
     * @param  string $password (required)
     * @param  string $action (required)
     * @param  int $timestamp (required)
     * @param  string $allow_origin_url (required)
     * @param  double $amount (required)
     * @param  string $original_tx_id (optional)
     * @param  string $original_merchant_tx_id (optional)
     * @param  string $agent_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSessionTokenRequest($merchant_id, $password, $action, $timestamp, $allow_origin_url, $amount, $original_tx_id = null, $original_merchant_tx_id = null, $agent_id = null)
    {
        // verify the required parameter 'merchant_id' is set
        if ($merchant_id === null || (is_array($merchant_id) && count($merchant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $merchant_id when calling getSessionToken'
            );
        }
        // verify the required parameter 'password' is set
        if ($password === null || (is_array($password) && count($password) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $password when calling getSessionToken'
            );
        }
        // verify the required parameter 'action' is set
        if ($action === null || (is_array($action) && count($action) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $action when calling getSessionToken'
            );
        }
        // verify the required parameter 'timestamp' is set
        if ($timestamp === null || (is_array($timestamp) && count($timestamp) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $timestamp when calling getSessionToken'
            );
        }
        // verify the required parameter 'allow_origin_url' is set
        if ($allow_origin_url === null || (is_array($allow_origin_url) && count($allow_origin_url) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $allow_origin_url when calling getSessionToken'
            );
        }
        // verify the required parameter 'amount' is set
        if ($amount === null || (is_array($amount) && count($amount) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $amount when calling getSessionToken'
            );
        }

        $resourcePath = '/token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($merchant_id !== null) {
            $formParams['merchantId'] = ObjectSerializer::toFormValue($merchant_id);
        }
        // form params
        if ($password !== null) {
            $formParams['password'] = ObjectSerializer::toFormValue($password);
        }
        // form params
        if ($action !== null) {
            $formParams['action'] = ObjectSerializer::toFormValue($action);
        }
        // form params
        if ($timestamp !== null) {
            $formParams['timestamp'] = ObjectSerializer::toFormValue($timestamp);
        }
        // form params
        if ($allow_origin_url !== null) {
            $formParams['allowOriginUrl'] = ObjectSerializer::toFormValue($allow_origin_url);
        }
        // form params
        if ($original_tx_id !== null) {
            $formParams['originalTxId'] = ObjectSerializer::toFormValue($original_tx_id);
        }
        // form params
        if ($original_merchant_tx_id !== null) {
            $formParams['originalMerchantTxId'] = ObjectSerializer::toFormValue($original_merchant_tx_id);
        }
        // form params
        if ($agent_id !== null) {
            $formParams['agentId'] = ObjectSerializer::toFormValue($agent_id);
        }
        // form params
        if ($amount !== null) {
            $formParams['amount'] = ObjectSerializer::toFormValue($amount);
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
