/*
 * EVO Payments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Evopayments.Client.OpenAPIDateConverter;

namespace Com.Evopayments.Model
{
    /// <summary>
    /// ResponseNotProcessed
    /// </summary>
    [DataContract]
    public partial class ResponseNotProcessed : BaseResponse,  IEquatable<ResponseNotProcessed>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseNotProcessed" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResponseNotProcessed() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseNotProcessed" /> class.
        /// </summary>
        /// <param name="merchantId">merchantId.</param>
        /// <param name="processingTime">processingTime.</param>
        public ResponseNotProcessed(string merchantId = default(string), int processingTime = default(int), string result = "ResponseNotProcessed") : base(result)
        {
            this.MerchantId = merchantId;
            this.ProcessingTime = processingTime;
        }

        /// <summary>
        /// Gets or Sets MerchantId
        /// </summary>
        [DataMember(Name="merchantId", EmitDefaultValue=false)]
        public string MerchantId { get; set; }

        /// <summary>
        /// Gets or Sets ProcessingTime
        /// </summary>
        [DataMember(Name="processingTime", EmitDefaultValue=false)]
        public int ProcessingTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResponseNotProcessed {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  ProcessingTime: ").Append(ProcessingTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResponseNotProcessed);
        }

        /// <summary>
        /// Returns true if ResponseNotProcessed instances are equal
        /// </summary>
        /// <param name="input">Instance of ResponseNotProcessed to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResponseNotProcessed input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.MerchantId == input.MerchantId ||
                    (this.MerchantId != null &&
                    this.MerchantId.Equals(input.MerchantId))
                ) && base.Equals(input) && 
                (
                    this.ProcessingTime == input.ProcessingTime ||
                    (this.ProcessingTime != null &&
                    this.ProcessingTime.Equals(input.ProcessingTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.MerchantId != null)
                    hashCode = hashCode * 59 + this.MerchantId.GetHashCode();
                if (this.ProcessingTime != null)
                    hashCode = hashCode * 59 + this.ProcessingTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
