/*
 * EVO Payments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Com.Evopayments.Client;
using Com.Evopayments.Api;
using Com.Evopayments.Model;

namespace Com.Evopayments.Test
{
    /// <summary>
    ///  Class for testing PaymentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PaymentApiTests
    {
        private PaymentApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PaymentApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' PaymentApi
            //Assert.IsInstanceOf(typeof(PaymentApi), instance);
        }

        
        /// <summary>
        /// Test CapturePayment
        /// </summary>
        [Test]
        public void CapturePaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int merchantId = null;
            //string token = null;
            //string action = null;
            //var response = instance.CapturePayment(merchantId, token, action);
            //Assert.IsInstanceOf(typeof(BaseResponse), response, "response is BaseResponse");
        }
        
    }

}
