/*
 * EVO Payments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Evopayments.Api;
using Com.Evopayments.Model;
using Com.Evopayments.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Evopayments.Test
{
    /// <summary>
    ///  Class for testing TokenResponseProcessed
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenResponseProcessedTests
    {
        // TODO uncomment below to declare an instance variable for TokenResponseProcessed
        //private TokenResponseProcessed instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TokenResponseProcessed
            //instance = new TokenResponseProcessed();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TokenResponseProcessed
        /// </summary>
        [Test]
        public void TokenResponseProcessedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TokenResponseProcessed
            //Assert.IsInstanceOf(typeof(TokenResponseProcessed), instance);
        }


        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Test]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Test]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'ResultId'
        /// </summary>
        [Test]
        public void ResultIdTest()
        {
            // TODO unit test for the property 'ResultId'
        }
        /// <summary>
        /// Test the property 'ProcessingTime'
        /// </summary>
        [Test]
        public void ProcessingTimeTest()
        {
            // TODO unit test for the property 'ProcessingTime'
        }

    }

}
