/*
 * EVO Payments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.evopayments.api;

import com.evopayments.ApiException;
import com.evopayments.model.BaseResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentApi
 */
@Ignore
public class PaymentApiTest {

    private final PaymentApi api = new PaymentApi();

    
    /**
     * 
     *
     * Process payment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void capturePaymentTest() throws ApiException {
        Integer merchantId = null;
        String token = null;
        String action = null;
                BaseResponse response = api.capturePayment(merchantId, token, action)
                .execute();
        // TODO: test validations
    }
    
}
