/*
 * EVO Payments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Com.Evopayments.Client;
using Com.Evopayments.Model;

namespace Com.Evopayments.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITokenApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch session token
        /// </remarks>
        /// <exception cref="Com.Evopayments.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="password"></param>
        /// <param name="action"></param>
        /// <param name="timestamp"></param>
        /// <param name="allowOriginUrl"></param>
        /// <param name="amount"></param>
        /// <param name="originalTxId"> (optional)</param>
        /// <param name="originalMerchantTxId"> (optional)</param>
        /// <param name="agentId"> (optional)</param>
        /// <returns>BaseResponse</returns>
        BaseResponse GetSessionToken (int merchantId, string password, string action, int timestamp, string allowOriginUrl, double amount, string originalTxId = default(string), string originalMerchantTxId = default(string), string agentId = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch session token
        /// </remarks>
        /// <exception cref="Com.Evopayments.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="password"></param>
        /// <param name="action"></param>
        /// <param name="timestamp"></param>
        /// <param name="allowOriginUrl"></param>
        /// <param name="amount"></param>
        /// <param name="originalTxId"> (optional)</param>
        /// <param name="originalMerchantTxId"> (optional)</param>
        /// <param name="agentId"> (optional)</param>
        /// <returns>ApiResponse of BaseResponse</returns>
        ApiResponse<BaseResponse> GetSessionTokenWithHttpInfo (int merchantId, string password, string action, int timestamp, string allowOriginUrl, double amount, string originalTxId = default(string), string originalMerchantTxId = default(string), string agentId = default(string));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch session token
        /// </remarks>
        /// <exception cref="Com.Evopayments.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="password"></param>
        /// <param name="action"></param>
        /// <param name="timestamp"></param>
        /// <param name="allowOriginUrl"></param>
        /// <param name="amount"></param>
        /// <param name="originalTxId"> (optional)</param>
        /// <param name="originalMerchantTxId"> (optional)</param>
        /// <param name="agentId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of BaseResponse</returns>
        System.Threading.Tasks.Task<BaseResponse> GetSessionTokenAsync (int merchantId, string password, string action, int timestamp, string allowOriginUrl, double amount, string originalTxId = default(string), string originalMerchantTxId = default(string), string agentId = default(string), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Fetch session token
        /// </remarks>
        /// <exception cref="Com.Evopayments.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="password"></param>
        /// <param name="action"></param>
        /// <param name="timestamp"></param>
        /// <param name="allowOriginUrl"></param>
        /// <param name="amount"></param>
        /// <param name="originalTxId"> (optional)</param>
        /// <param name="originalMerchantTxId"> (optional)</param>
        /// <param name="agentId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (BaseResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BaseResponse>> GetSessionTokenWithHttpInfoAsync (int merchantId, string password, string action, int timestamp, string allowOriginUrl, double amount, string originalTxId = default(string), string originalMerchantTxId = default(string), string agentId = default(string), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TokenApi : ITokenApi
    {
        private Com.Evopayments.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TokenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TokenApi(String basePath)
        {
            this.Configuration = new Com.Evopayments.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Com.Evopayments.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TokenApi"/> class
        /// </summary>
        /// <returns></returns>
        public TokenApi()
        {
            this.Configuration = Com.Evopayments.Client.Configuration.Default;

            ExceptionFactory = Com.Evopayments.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TokenApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TokenApi(Com.Evopayments.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Com.Evopayments.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Com.Evopayments.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Com.Evopayments.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Com.Evopayments.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Fetch session token
        /// </summary>
        /// <exception cref="Com.Evopayments.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="password"></param>
        /// <param name="action"></param>
        /// <param name="timestamp"></param>
        /// <param name="allowOriginUrl"></param>
        /// <param name="amount"></param>
        /// <param name="originalTxId"> (optional)</param>
        /// <param name="originalMerchantTxId"> (optional)</param>
        /// <param name="agentId"> (optional)</param>
        /// <returns>BaseResponse</returns>
        public BaseResponse GetSessionToken (int merchantId, string password, string action, int timestamp, string allowOriginUrl, double amount, string originalTxId = default(string), string originalMerchantTxId = default(string), string agentId = default(string))
        {
             ApiResponse<BaseResponse> localVarResponse = GetSessionTokenWithHttpInfo(merchantId, password, action, timestamp, allowOriginUrl, amount, originalTxId, originalMerchantTxId, agentId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Fetch session token
        /// </summary>
        /// <exception cref="Com.Evopayments.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="password"></param>
        /// <param name="action"></param>
        /// <param name="timestamp"></param>
        /// <param name="allowOriginUrl"></param>
        /// <param name="amount"></param>
        /// <param name="originalTxId"> (optional)</param>
        /// <param name="originalMerchantTxId"> (optional)</param>
        /// <param name="agentId"> (optional)</param>
        /// <returns>ApiResponse of BaseResponse</returns>
        public ApiResponse<BaseResponse> GetSessionTokenWithHttpInfo (int merchantId, string password, string action, int timestamp, string allowOriginUrl, double amount, string originalTxId = default(string), string originalMerchantTxId = default(string), string agentId = default(string))
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new ApiException(400, "Missing required parameter 'merchantId' when calling TokenApi->GetSessionToken");
            // verify the required parameter 'password' is set
            if (password == null)
                throw new ApiException(400, "Missing required parameter 'password' when calling TokenApi->GetSessionToken");
            // verify the required parameter 'action' is set
            if (action == null)
                throw new ApiException(400, "Missing required parameter 'action' when calling TokenApi->GetSessionToken");
            // verify the required parameter 'timestamp' is set
            if (timestamp == null)
                throw new ApiException(400, "Missing required parameter 'timestamp' when calling TokenApi->GetSessionToken");
            // verify the required parameter 'allowOriginUrl' is set
            if (allowOriginUrl == null)
                throw new ApiException(400, "Missing required parameter 'allowOriginUrl' when calling TokenApi->GetSessionToken");
            // verify the required parameter 'amount' is set
            if (amount == null)
                throw new ApiException(400, "Missing required parameter 'amount' when calling TokenApi->GetSessionToken");

            var localVarPath = "/token";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (merchantId != null) localVarFormParams.Add("merchantId", this.Configuration.ApiClient.ParameterToString(merchantId)); // form parameter
            if (password != null) localVarFormParams.Add("password", this.Configuration.ApiClient.ParameterToString(password)); // form parameter
            if (action != null) localVarFormParams.Add("action", this.Configuration.ApiClient.ParameterToString(action)); // form parameter
            if (timestamp != null) localVarFormParams.Add("timestamp", this.Configuration.ApiClient.ParameterToString(timestamp)); // form parameter
            if (allowOriginUrl != null) localVarFormParams.Add("allowOriginUrl", this.Configuration.ApiClient.ParameterToString(allowOriginUrl)); // form parameter
            if (originalTxId != null) localVarFormParams.Add("originalTxId", this.Configuration.ApiClient.ParameterToString(originalTxId)); // form parameter
            if (originalMerchantTxId != null) localVarFormParams.Add("originalMerchantTxId", this.Configuration.ApiClient.ParameterToString(originalMerchantTxId)); // form parameter
            if (agentId != null) localVarFormParams.Add("agentId", this.Configuration.ApiClient.ParameterToString(agentId)); // form parameter
            if (amount != null) localVarFormParams.Add("amount", this.Configuration.ApiClient.ParameterToString(amount)); // form parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSessionToken", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BaseResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (BaseResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BaseResponse)));
        }

        /// <summary>
        ///  Fetch session token
        /// </summary>
        /// <exception cref="Com.Evopayments.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="password"></param>
        /// <param name="action"></param>
        /// <param name="timestamp"></param>
        /// <param name="allowOriginUrl"></param>
        /// <param name="amount"></param>
        /// <param name="originalTxId"> (optional)</param>
        /// <param name="originalMerchantTxId"> (optional)</param>
        /// <param name="agentId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of BaseResponse</returns>
        public async System.Threading.Tasks.Task<BaseResponse> GetSessionTokenAsync (int merchantId, string password, string action, int timestamp, string allowOriginUrl, double amount, string originalTxId = default(string), string originalMerchantTxId = default(string), string agentId = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<BaseResponse> localVarResponse = await GetSessionTokenWithHttpInfoAsync(merchantId, password, action, timestamp, allowOriginUrl, amount, originalTxId, originalMerchantTxId, agentId, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Fetch session token
        /// </summary>
        /// <exception cref="Com.Evopayments.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId"></param>
        /// <param name="password"></param>
        /// <param name="action"></param>
        /// <param name="timestamp"></param>
        /// <param name="allowOriginUrl"></param>
        /// <param name="amount"></param>
        /// <param name="originalTxId"> (optional)</param>
        /// <param name="originalMerchantTxId"> (optional)</param>
        /// <param name="agentId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (BaseResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BaseResponse>> GetSessionTokenWithHttpInfoAsync (int merchantId, string password, string action, int timestamp, string allowOriginUrl, double amount, string originalTxId = default(string), string originalMerchantTxId = default(string), string agentId = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new ApiException(400, "Missing required parameter 'merchantId' when calling TokenApi->GetSessionToken");
            // verify the required parameter 'password' is set
            if (password == null)
                throw new ApiException(400, "Missing required parameter 'password' when calling TokenApi->GetSessionToken");
            // verify the required parameter 'action' is set
            if (action == null)
                throw new ApiException(400, "Missing required parameter 'action' when calling TokenApi->GetSessionToken");
            // verify the required parameter 'timestamp' is set
            if (timestamp == null)
                throw new ApiException(400, "Missing required parameter 'timestamp' when calling TokenApi->GetSessionToken");
            // verify the required parameter 'allowOriginUrl' is set
            if (allowOriginUrl == null)
                throw new ApiException(400, "Missing required parameter 'allowOriginUrl' when calling TokenApi->GetSessionToken");
            // verify the required parameter 'amount' is set
            if (amount == null)
                throw new ApiException(400, "Missing required parameter 'amount' when calling TokenApi->GetSessionToken");

            var localVarPath = "/token";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (merchantId != null) localVarFormParams.Add("merchantId", this.Configuration.ApiClient.ParameterToString(merchantId)); // form parameter
            if (password != null) localVarFormParams.Add("password", this.Configuration.ApiClient.ParameterToString(password)); // form parameter
            if (action != null) localVarFormParams.Add("action", this.Configuration.ApiClient.ParameterToString(action)); // form parameter
            if (timestamp != null) localVarFormParams.Add("timestamp", this.Configuration.ApiClient.ParameterToString(timestamp)); // form parameter
            if (allowOriginUrl != null) localVarFormParams.Add("allowOriginUrl", this.Configuration.ApiClient.ParameterToString(allowOriginUrl)); // form parameter
            if (originalTxId != null) localVarFormParams.Add("originalTxId", this.Configuration.ApiClient.ParameterToString(originalTxId)); // form parameter
            if (originalMerchantTxId != null) localVarFormParams.Add("originalMerchantTxId", this.Configuration.ApiClient.ParameterToString(originalMerchantTxId)); // form parameter
            if (agentId != null) localVarFormParams.Add("agentId", this.Configuration.ApiClient.ParameterToString(agentId)); // form parameter
            if (amount != null) localVarFormParams.Add("amount", this.Configuration.ApiClient.ParameterToString(amount)); // form parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSessionToken", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BaseResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (BaseResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BaseResponse)));
        }

    }
}
